/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package sn.academy.food_delivery.models.avro;
@org.apache.avro.specific.AvroGenerated
public enum CardType implements org.apache.avro.generic.GenericEnumSymbol<CardType> {
  MASTERCARD, AMEX, VISA, DISCOVER  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"CardType\",\"namespace\":\"sn.academy.food_delivery.models.avro\",\"symbols\":[\"MASTERCARD\",\"AMEX\",\"VISA\",\"DISCOVER\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
