/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package sn.academy.food_delivery.models.avro;

@org.apache.avro.specific.AvroGenerated
public interface CommonsProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"CommonsProtocol\",\"namespace\":\"sn.academy.food_delivery.models.avro\",\"types\":[{\"type\":\"record\",\"name\":\"Address\",\"fields\":[{\"name\":\"street\",\"type\":\"string\"},{\"name\":\"city\",\"type\":\"string\"},{\"name\":\"state\",\"type\":\"string\"},{\"name\":\"zip\",\"type\":\"string\"}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends CommonsProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = sn.academy.food_delivery.models.avro.CommonsProtocol.PROTOCOL;
  }
}