/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package sn.academy.food_delivery.models.avro;

@org.apache.avro.specific.AvroGenerated
public interface GeoProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"GeoProtocol\",\"namespace\":\"sn.academy.food_delivery.models.avro\",\"types\":[{\"type\":\"record\",\"name\":\"GeoLocation\",\"fields\":[{\"name\":\"latitude\",\"type\":\"double\"},{\"name\":\"longitude\",\"type\":\"double\"}]},{\"type\":\"record\",\"name\":\"Address\",\"fields\":[{\"name\":\"street\",\"type\":\"string\"},{\"name\":\"city\",\"type\":\"string\"},{\"name\":\"state\",\"type\":\"string\"},{\"name\":\"country\",\"type\":\"string\"},{\"name\":\"zip\",\"type\":\"string\"}]},{\"type\":\"record\",\"name\":\"GeoEncodedAddress\",\"fields\":[{\"name\":\"address\",\"type\":\"Address\"},{\"name\":\"isValidAddress\",\"type\":\"boolean\"},{\"name\":\"geoLocation\",\"type\":[\"null\",\"GeoLocation\"]}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends GeoProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = sn.academy.food_delivery.models.avro.GeoProtocol.PROTOCOL;
  }
}