/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package sn.academy.food_delivery.models.avro;

@org.apache.avro.specific.AvroGenerated
public interface RestaurantsProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"RestaurantsProtocol\",\"namespace\":\"sn.academy.food_delivery.models.avro\",\"types\":[{\"type\":\"record\",\"name\":\"MenuItem\",\"fields\":[{\"name\":\"item_id\",\"type\":\"int\"},{\"name\":\"item_name\",\"type\":\"string\"},{\"name\":\"item_description\",\"type\":\"string\"},{\"name\":\"price\",\"type\":\"float\"}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends RestaurantsProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = sn.academy.food_delivery.models.avro.RestaurantsProtocol.PROTOCOL;
  }
}